export const ERROR_CODES = {
  INTERNAL_SERVER_ERROR: 500,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,

  USER_NOT_FOUND: 1001,
  INVALID_CREDENTIALS: 1002,
  PRODUCT_OUT_OF_STOCK: 2001,
  ORDER_ALREADY_PROCESSED: 3001,
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
